### ISSUE TITLE
Check if article were updated

### ISSUE THREAD

**Issue by PAException** [engelsburg/engelsburg-api#60]
Possible implementation:
- Hash of article saved along
- Every intervall service checks if changend and fetches updated

**Comment by PAException** [comment]
@dariotrombello implement or nah?

**Comment by dariotrombello** [comment]
Wenn du nichts zu tun hast 😂

**Comment by PAException** [comment]
> Wenn du nichts zu tun hast 😂

mal gucken :D

**Comment by PAException** [comment]
use ids to check for changes and app usage
